name: Coverage

on: [pull_request, push]

jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: rustup update stable

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      
      - name: Set date variable
        id: date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
        
      - name: Build project
        run: cargo build --release
        
      - name: Generate code coverage
        run: RUSTFLAGS="--remap-path-prefix=$(pwd)=." cargo llvm-cov --all-features --html --output-dir coverage
        
      - name: Upload Coverage Report as Artifact
        id: upload_artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/

      - name: create folder
        run: mkdir ./public
      
      - name: organize folder
        run: mv coverage/html/* coverage/
      
      - name: remove html folder
        run: rmdir coverage/html

      - name: Extract Function Coverage
        run: |
          # Extract the Function Coverage value using sed
          function_coverage=$(sed -n 's/.*Function Coverage[^0-9]*\([0-9.]*%\).*/\1/p' coverage/index.html)
    
          # Print the Function Coverage value to the logs
          if [ -z "$function_coverage" ]; then
            echo "Function Coverage not found."
          else
            echo "Function Coverage: $function_coverage"
          fi


      - name: move index.html
        run: mv coverage/* ./public/

      
        
      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./public
            publish_branch: gh-pages

      - name: Post Coverage Report as GitHub Issue
        uses: dacbd/create-issue-action@main
        with:
              token: ${{ github.token }}
              title: "Biweekly Code Coverage Report - ${{ env.DATE }}"
              body:  A detailed report has been generated.
                You can see the full report [here](https://fabianschwaiger-dm.github.io/test/).
              labels: coverage, automated-report
