name: Coverage

on: [pull_request, push]

jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: rustup update stable

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
        
      - name: Build project
        run: cargo build --release
        
      - name: Generate code coverage
        run: cargo llvm-cov --all-features --html
        
      - name: Upload Coverage Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: target/llvm-cov/html/index.html
      
      - name: Set date variable
        id: date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
        
      - name: Post Coverage Report as GitHub Issue
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ github.token }}
          title: "Biweekly Code Coverage Report - ${{ env.DATE }}"
          body:  A detailed report has been generated.
            You can download the full report [here](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ steps.artifact-upload-step.outputs.artifact-id }}).
          labels: coverage, automated-report
